Ag  add cart broken
ruriona19/wdd330-team04 pull request #6
Opened 2023-09-22 23:38 UTC by galiciaabraham

2023-09-23 01:25 UTC, adcostanzi approved these changes
Excelent work Abraham!
To be honest I couldnñt think on a proper way to implement the array and I got too lazy. I'm glad you showed me a proper way to do it. Great coding! You inspired me to work harder on these kind of assigments!

2023-09-23 14:42 UTC, ruriona19 commented on src/js/product.js
Good job in adding this function. You helped me realize that it is better to check whether the cart is empty or not by reviewing the data in the localStorage

2023-09-23 15:00 UTC, ruriona19 requested changes

2023-09-23 15:00 UTC, ruriona19 commented on src/js/product.js
> +  }
This piece of code works fine. I can suggest you to avoid duplicate code  and enhance your function as follows:

function addProductToCart(product) {
    let orderedItems;
    if (checkCart("so-cart") == true) {
       orderedItems.push(product);
       orderedItems = getLocalStorage("so-cart");
    } else {
        orderdItems = [];
    }

    orderedItems.push(product);
    setLocalStorage("so-cart", orderedItems);
}

2023-09-23 15:00 UTC, ruriona19 commented on src/js/cart.js
> +  const cartItems = [getLocalStorage("so-cart")];
Although the application runs correctly with these changes, it is not necessary to wrap 'getLocalSotarage("so-cart")' with square brackets.  What you get from "so-cart" is already an array. So you are getting a nested array here, that is why you had to add an extra map in lines 6 and 7 to loop in this nested array.

Basically none change is necessary in this js file. All the changes you did in product.js is enough to fix the issue related to cart broken trello card

2023-09-29 17:09 UTC, closed without merging

2023-09-29 17:11 UTC, galiciaabraham commented
Pull request can be deleted since we've merged a different solution